openapi: 3.0.0
info:
  title: Login API
  description: API for user authentication
  version: 1.0.0
paths:
  /api/login:
    post:
      summary: User Login
      description: Authenticates a user and returns user details.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - password
              properties:
                user_id:
                  type: string
                  description: User ID
                  example: "test_user"
                password:
                  type: string
                  description: User Password
                  example: "password123"
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: Internal User ID
                    example: 1
                  user_id:
                    type: string
                    description: User ID
                    example: "test_user"
                  user_name:
                    type: string
                    description: Display Name
                    example: "Test User"
        '400':
          description: Invalid input or login failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "User not found"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Unexpected error"
