steps:
  # # build dao
  # - name: "gcr.io/cloud-builders/docker"
  #   dir: "./py"
  #   args:
  #     [
  #       "build",
  #       "-t",
  #       "northamerica-northeast1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/nikkipy:tag1",
  #       ".",
  #     ]
  # # push to artifact
  # - name: "gcr.io/cloud-builders/docker"
  #   dir: "./py"
  #   args:
  #     [
  #       "push",
  #       "northamerica-northeast1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/nikkipy:tag1",
  #     ]
  # build submit
  - name: "gcr.io/cloud-builders/gcloud"
    dir: "./py"
    args:
      - "builds"
      - "submit"
      - "--region"
      - "="
      - "northamerica-northeast1"
      - "--tag" # cloud run service name
      - "northamerica-northeast1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/nikkipy:tag1"
      - "."
  # deploy by cloud run
  - name: "gcr.io/cloud-builders/gcloud"
    dir: "./py"
    args:
      - "run"
      - "deploy"
      - "nikkipy" # cloud run service name
      - "--image"
      - "northamerica-northeast1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/nikkipy:tag1"
      - "--region"
      - "northamerica-northeast1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
images:
  - "northamerica-northeast1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/nikkipy:tag1"
