steps:
  # build
  - name: "gcr.io/cloud-builders/docker"
    dir: "./py"
    args:
      [
        "build",
        "--build-arg",
        "DATABASE_URI=${_DATABASE_URI}",
        "-t",
        "northamerica-northeast1-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_ID}/nikkipy",
        ".",
      ]
  # push to artifact
  - name: "gcr.io/cloud-builders/docker"
    dir: "./py"
    args:
      [
        "push",
        "northamerica-northeast1-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_ID}/nikkipy",
      ]
  # deploy by cloud run
  - name: "gcr.io/cloud-builders/gcloud"
    dir: "./py"
    args:
      - "run"
      - "deploy"
      - "nikkipy" # cloud run service name
      - "--image"
      - "northamerica-northeast1-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_ID}/nikkipy"
      - "--region"
      - "northamerica-northeast1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
images:
  - "northamerica-northeast1-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_ID}/nikkipy"
