"""delete nikki relationship from tag table

Revision ID: 75be59e86cdb
Revises: d4fe665abc80
Create Date: 2022-12-14 09:23:21.786080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75be59e86cdb'
down_revision = 'd4fe665abc80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """ Tag.nikkis のrelationship を削除した。
    dbでなくて、sqlalchemy の中の問題っぽい・
    """
    # ### commands auto generated by Alembic - please adjust! ###
    # Nikkiで tags = relationship("Tag", secondary=nikkitag_table,  back_populates="nikkis") ->
    # tags = relationship("Tag", secondary=nikkitag_table,)
    # Tagのcolumnで、 nikkis = relationship("Nikki", secondary=nikkitag_table, back_populates="tags") を削除
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """ Tag.nikkis のrelationship を削除した。
    dbでなくて、sqlalchemy の中の問題っぽい。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    # upgrade で削除した部分を追加すること
    pass
    # ### end Alembic commands ###
