"""add tag table's created_by column to nullable=False 

Revision ID: 92cb9a3fc6df
Revises: 4bc6b716d115
Create Date: 2022-12-04 09:08:41.353606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92cb9a3fc6df'
down_revision = '4bc6b716d115'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """ タグテーブルのcreated_by にnullable=False 追加
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'created_by',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """ タグテーブルのcreated_by をnullable=Fakse -> True
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'created_by',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
