"""change nikkitag table relationship table

Revision ID: d4fe665abc80
Revises: 7d9e44394524
Create Date: 2022-12-05 19:51:04.068945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4fe665abc80'
down_revision = '7d9e44394524'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nikkitag', sa.Column('nikki_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'nikkitag', 'tag', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'nikkitag', 'nikki', ['nikki_id'], ['id'])
    op.drop_column('nikkitag', 'niiki_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nikkitag', sa.Column('niiki_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'nikkitag', type_='foreignkey')
    op.drop_constraint(None, 'nikkitag', type_='foreignkey')
    op.drop_column('nikkitag', 'nikki_id')
    # ### end Alembic commands ###
